import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { copyFileSync } from "node:fs";
import process from "node:process";

const CONFIG_SRC = "config.example.json";
const CONFIG_DEST = "config.local.json";
const ENV_FILE = ".env";

const noAuth = process.argv.includes("--no-auth");

// ---------------------------------------------------------------------------
// 1. Copy starter config if it doesn't already exist
// ---------------------------------------------------------------------------

if (!existsSync(CONFIG_DEST)) {
  copyFileSync(CONFIG_SRC, CONFIG_DEST);
  globalThis.console.log(`Created ${CONFIG_DEST}`);
} else {
  globalThis.console.log(`${CONFIG_DEST} already exists – keeping existing config`);
}

if (noAuth) {
  globalThis.console.log("Skipping token generation (--no-auth)");
  process.exit(0);
}

// ---------------------------------------------------------------------------
// 2. Read existing .env (if any) so we can preserve all current values
// ---------------------------------------------------------------------------

/** @type {Map<string, string>} */
const envEntries = new Map();
/** @type {string[]} Preserves comment / blank lines for readability */
const rawLines = [];

if (existsSync(ENV_FILE)) {
  const raw = readFileSync(ENV_FILE, "utf8");

  for (const line of raw.split(/\r?\n/)) {
    rawLines.push(line);
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) {
      continue;
    }
    const eqIdx = trimmed.indexOf("=");
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim();
    if (key) {
      envEntries.set(key, val);
    }
  }
}

// ---------------------------------------------------------------------------
// 3. Generate tokens when they are absent
// ---------------------------------------------------------------------------

/** @param {number} bytes */
function generateHex(bytes) {
  return randomBytes(bytes).toString("hex");
}

/** @param {string} token */
function maskToken(token) {
  if (token.length <= 8) {
    return "****";
  }
  return `${token.slice(0, 4)}...${token.slice(-4)}`;
}

let generated = false;

if (!envEntries.has("GPT_REPO_ACCESS_TOKEN")) {
  const token = generateHex(32); // 64 hex chars
  envEntries.set("GPT_REPO_ACCESS_TOKEN", token);
  globalThis.console.log(`Generated GPT_REPO_ACCESS_TOKEN  ${maskToken(token)}`);
  generated = true;
} else {
  globalThis.console.log("GPT_REPO_ACCESS_TOKEN already set – keeping existing value");
}

if (!envEntries.has("GPT_REPO_PUBLIC_PATH_TOKEN")) {
  const token = generateHex(16); // 32 hex chars
  envEntries.set("GPT_REPO_PUBLIC_PATH_TOKEN", token);
  globalThis.console.log(`Generated GPT_REPO_PUBLIC_PATH_TOKEN  ${maskToken(token)}`);
  generated = true;
} else {
  globalThis.console.log("GPT_REPO_PUBLIC_PATH_TOKEN already set – keeping existing value");
}

// ---------------------------------------------------------------------------
// 4. Write .env (merge generated entries into existing file content)
// ---------------------------------------------------------------------------

const MANAGED_KEYS = new Set(["GPT_REPO_ACCESS_TOKEN", "GPT_REPO_PUBLIC_PATH_TOKEN"]);

// Remove managed keys from existing raw lines (we will append/update them)
const filteredLines = rawLines.filter((line) => {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) {
    return true;
  }
  const key = trimmed.slice(0, trimmed.indexOf("=")).trim();
  return !MANAGED_KEYS.has(key);
});

// Trim trailing blank lines from the preserved content
while (filteredLines.length > 0 && filteredLines[filteredLines.length - 1].trim() === "") {
  filteredLines.pop();
}

const authBlock = [
  "",
  "# Auth tokens generated by npm run setup:config",
  `GPT_REPO_ACCESS_TOKEN=${envEntries.get("GPT_REPO_ACCESS_TOKEN")}`,
  `GPT_REPO_PUBLIC_PATH_TOKEN=${envEntries.get("GPT_REPO_PUBLIC_PATH_TOKEN")}`,
  ""
];

const newContent = [...filteredLines, ...authBlock].join("\n");
writeFileSync(ENV_FILE, newContent, "utf8");

if (generated) {
  globalThis.console.log(`Saved to ${ENV_FILE}`);
  globalThis.console.log("Secrets were generated and saved – check .env if you need them");
} else {
  globalThis.console.log(`${ENV_FILE} is up to date`);
}
